from __future__ import annotations
import torch
import torch._C.cpp.nn
import typing
__all__: list[str] = ['MultiHeadAttention', 'NormalizedLinear', 'PositionalEmbedding']
class MultiHeadAttention(torch._C.cpp.nn.Module):
    def __init__(self, d_q: typing.SupportsInt | typing.SupportsIndex, d_k: typing.SupportsInt | typing.SupportsIndex, d_v: typing.SupportsInt | typing.SupportsIndex, d_head: typing.SupportsInt | typing.SupportsIndex, nheads: typing.SupportsInt | typing.SupportsIndex, dropout: typing.SupportsFloat | typing.SupportsIndex = 0.0, bias: bool = True, device: torch.device = ..., dtype: torch.dtype = ...) -> None:
        ...
    def forward(self, arg0: torch.Tensor, arg1: torch.Tensor, arg2: torch.Tensor, arg3: torch.Tensor | None, arg4: bool) -> torch.Tensor:
        ...
    def load_weights(self, arg0: str) -> None:
        ...
    def save_weights(self, arg0: str) -> None:
        ...
class NormalizedLinear(torch._C.cpp.nn.Module):
    def __init__(self, d_in: typing.SupportsInt | typing.SupportsIndex, d_out: typing.SupportsInt | typing.SupportsIndex, divisor: typing.SupportsFloat | typing.SupportsIndex = 400.0, device: torch.device = ..., dtype: torch.dtype = ...) -> None:
        ...
    def forward(self, arg0: torch.Tensor) -> torch.Tensor:
        ...
    def load_weights(self, arg0: str) -> None:
        ...
    def save_weights(self, arg0: str) -> None:
        ...
class PositionalEmbedding(torch._C.cpp.nn.Module):
    def __init__(self, d_model: typing.SupportsInt | typing.SupportsIndex, dropout: typing.SupportsFloat | typing.SupportsIndex = 0.1, max_len: typing.SupportsInt | typing.SupportsIndex = 5000, device: torch.device = ..., dtype: torch.dtype = ...) -> None:
        ...
    def forward(self, arg0: torch.Tensor) -> torch.Tensor:
        ...
