from __future__ import annotations
import collections.abc
import torch
import torch._C.cpp.nn
import typing
__all__: list[str] = ['AdjacencyMatrices', 'AttackDataEmbedding', 'CardAmountDataEmbedding', 'CardEmbedding', 'CardPositionEmbedding', 'CardStateEmbedding', 'ConditionEmbedding', 'DiscardDataEmbedding', 'FilterConditionEmbedding', 'FilterEmbedding', 'GameEmbedding', 'InstructionDataEmbedding', 'InstructionEmbedding', 'MultiHeadAttention', 'NormalizedLinear', 'PlayerStateEmbedding', 'PlayerTargetDataEmbedding', 'PositionalEmbedding', 'ReturnToDeckTypeDataEmbedding', 'SharedEmbeddingHolder', 'make_card_embedding', 'make_card_state_embedding', 'nesting_flatten_filter', 'nesting_reduce', 'nesting_traverse_filter']
class AdjacencyMatrices:
    @property
    def attached_energy_adjacency(self) -> torch.Tensor:
        ...
    @property
    def evolves_from_adjacency(self) -> torch.Tensor:
        ...
    @property
    def pre_evolutions_adjacency(self) -> torch.Tensor:
        ...
class AttackDataEmbedding(torch._C.cpp.nn.Module):
    def __init__(self, shared_embedding_holder: SharedEmbeddingHolder, dimension_out: typing.SupportsInt | typing.SupportsIndex, device: torch.device = ..., dtype: torch.dtype = ...) -> None:
        ...
    def forward(self, arg0: torch.Tensor) -> torch.Tensor:
        ...
    def load_weights(self, arg0: str) -> None:
        ...
    def save_weights(self, arg0: str) -> None:
        ...
class CardAmountDataEmbedding(torch._C.cpp.nn.Module):
    def __init__(self, shared_embedding_holder: SharedEmbeddingHolder, dimension_out: typing.SupportsInt | typing.SupportsIndex, device: torch.device = ..., dtype: torch.dtype = ...) -> None:
        ...
    def forward(self, arg0: torch.Tensor) -> torch.Tensor:
        ...
    def load_weights(self, arg0: str) -> None:
        ...
    def save_weights(self, arg0: str) -> None:
        ...
class CardEmbedding(torch._C.cpp.nn.Module):
    def forward(self, arg0: collections.abc.Iterable) -> tuple[torch.Tensor, AdjacencyMatrices, torch.Tensor, torch.Tensor]:
        """Return ``(embedding, adjacency, card_indices, segment_offsets)``.

        Single-game call: ``embedding`` is ``[num_cards, dim]``, ``card_indices`` is ``[1, max_deck_id+1]``.
        """
        ...
    def forward_batched(self, arg0: collections.abc.Iterable) -> tuple[torch.Tensor, AdjacencyMatrices, torch.Tensor, torch.Tensor]:
        """Batched cards flattened across games; ``segment_offsets`` has size ``B+1``."""
        ...
    def load_weights(self, arg0: str) -> None:
        ...
    def save_weights(self, arg0: str) -> None:
        ...
class CardPositionEmbedding(torch._C.cpp.nn.Module):
    def __init__(self, shared_embedding_holder: SharedEmbeddingHolder, dimension_out: typing.SupportsInt | typing.SupportsIndex, device: torch.device = ..., dtype: torch.dtype = ...) -> None:
        ...
    def forward(self, arg0: collections.abc.Iterable) -> torch.Tensor:
        ...
    def load_weights(self, arg0: str) -> None:
        ...
    def save_weights(self, arg0: str) -> None:
        ...
class CardStateEmbedding(torch._C.cpp.nn.Module):
    def forward(self, arg0: collections.abc.Iterable) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
        """Return ``(embedding, mask, card_indices)`` with shapes ``[B, max_cards, dim]``,
        ``[B, max_cards]``, and ``[B, max_deck_id+1]``. A single-game call uses ``B=1``."""
        ...
    def load_weights(self, arg0: str) -> None:
        ...
    def save_weights(self, arg0: str) -> None:
        ...
class ConditionEmbedding(torch._C.cpp.nn.Module):
    def __init__(self, instruction_data_embedding: InstructionDataEmbedding, shared_embedding_holder: SharedEmbeddingHolder, dimension_out: typing.SupportsInt | typing.SupportsIndex, device: torch.device = ..., dtype: torch.dtype = ...) -> None:
        ...
    def forward(self, arg0: collections.abc.Iterable) -> tuple[torch.Tensor, torch.Tensor]:
        ...
    def load_weights(self, arg0: str) -> None:
        ...
    def save_weights(self, arg0: str) -> None:
        ...
class DiscardDataEmbedding(torch._C.cpp.nn.Module):
    def __init__(self, dimension_out: typing.SupportsInt | typing.SupportsIndex, device: torch.device = ..., dtype: torch.dtype = ...) -> None:
        ...
    def forward(self, arg0: torch.Tensor) -> torch.Tensor:
        ...
    def load_weights(self, arg0: str) -> None:
        ...
    def save_weights(self, arg0: str) -> None:
        ...
class FilterConditionEmbedding(torch._C.cpp.nn.Module):
    def __init__(self, shared_embedding_holder: SharedEmbeddingHolder, dimension_out: typing.SupportsInt | typing.SupportsIndex, device: torch.device = ..., dtype: torch.dtype = ...) -> None:
        ...
    def forward(self, arg0: torch.Tensor, arg1: torch.Tensor, arg2: torch.Tensor) -> torch.Tensor:
        ...
    def load_weights(self, arg0: str) -> None:
        ...
    def save_weights(self, arg0: str) -> None:
        ...
class FilterEmbedding(torch._C.cpp.nn.Module):
    def __init__(self, shared_embedding_holder: SharedEmbeddingHolder, dimension_out: typing.SupportsInt | typing.SupportsIndex, device: torch.device = ..., dtype: torch.dtype = ...) -> None:
        ...
    def forward(self, arg0: collections.abc.Iterable) -> torch.Tensor:
        ...
    def load_weights(self, arg0: str) -> None:
        ...
    def save_weights(self, arg0: str) -> None:
        ...
class GameEmbedding(torch._C.cpp.nn.Module):
    def __init__(self, dimension_out: typing.SupportsInt | typing.SupportsIndex, device: torch.device = ..., dtype: torch.dtype = ...) -> None:
        ...
    def embedGameInteraction(
        self,
        game_interactions_per_game: collections.abc.Iterable,
        card_indices: torch.Tensor,
        cards: torch.Tensor,
    ) -> tuple[torch.Tensor, torch.Tensor]:
        """Embed legal interactions for a batch of game states.

        ``game_interactions_per_game`` is a list of per-game interaction lists (serialized protobuf).
        ``card_indices`` has shape ``[B, max_deck_id + 1]``; ``cards`` has shape ``[B, max_cards, dim]``
        (card rows only, from ``embedGameState``). Returns ``(embedding, mask)`` with shapes
        ``[B, max_interactions, dim]`` and ``[B, max_interactions]``.
        """
        ...
    def embedGameState(self, game_states: collections.abc.Iterable | bytes) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
        """Return ``(embedding, mask, card_indices)``.

        ``embedding`` shape is ``[B, 2 + max_cards, dimension_out]`` (player rows, then cards, padded).
        ``mask`` marks valid rows per game. ``card_indices`` has shape ``[B, max_deck_id + 1]``.
        A single serialized game state may be passed as raw ``bytes`` (wrapped as ``B=1``).
        """
        ...
    def load_weights(self, arg0: str) -> None:
        ...
    def save_weights(self, arg0: str) -> None:
        ...
class InstructionDataEmbedding(torch._C.cpp.nn.Module):
    def __init__(self, shared_embedding_holder: SharedEmbeddingHolder, dimension_out: typing.SupportsInt | typing.SupportsIndex, device: torch.device = ..., dtype: torch.dtype = ...) -> None:
        ...
    def forward(self, arg0: collections.abc.Iterable) -> torch.Tensor:
        ...
    def load_weights(self, arg0: str) -> None:
        ...
    def save_weights(self, arg0: str) -> None:
        ...
class InstructionEmbedding(torch._C.cpp.nn.Module):
    def __init__(self, instruction_data_embedding: InstructionDataEmbedding, shared_embedding_holder: SharedEmbeddingHolder, dimension_out: typing.SupportsInt | typing.SupportsIndex, device: torch.device = ..., dtype: torch.dtype = ...) -> None:
        ...
    def forward(self, arg0: collections.abc.Iterable) -> tuple[torch.Tensor, torch.Tensor]:
        ...
    def load_weights(self, arg0: str) -> None:
        ...
    def save_weights(self, arg0: str) -> None:
        ...
class MultiHeadAttention(torch._C.cpp.nn.Module):
    def __init__(self, d_q: typing.SupportsInt | typing.SupportsIndex, d_k: typing.SupportsInt | typing.SupportsIndex, d_v: typing.SupportsInt | typing.SupportsIndex, d_head: typing.SupportsInt | typing.SupportsIndex, nheads: typing.SupportsInt | typing.SupportsIndex, dropout: typing.SupportsFloat | typing.SupportsIndex = 0.0, bias: bool = True, device: torch.device = ..., dtype: torch.dtype = ...) -> None:
        ...
    def forward(self, arg0: torch.Tensor, arg1: torch.Tensor, arg2: torch.Tensor, arg3: torch.Tensor | None, arg4: bool) -> torch.Tensor:
        ...
    def load_weights(self, arg0: str) -> None:
        ...
    def save_weights(self, arg0: str) -> None:
        ...
class NormalizedLinear(torch._C.cpp.nn.Module):
    def __init__(self, d_in: typing.SupportsInt | typing.SupportsIndex, d_out: typing.SupportsInt | typing.SupportsIndex, divisor: typing.SupportsFloat | typing.SupportsIndex = 400.0, device: torch.device = ..., dtype: torch.dtype = ...) -> None:
        ...
    def forward(self, arg0: torch.Tensor) -> torch.Tensor:
        ...
    def load_weights(self, arg0: str) -> None:
        ...
    def save_weights(self, arg0: str) -> None:
        ...
class PlayerStateEmbedding(torch._C.cpp.nn.Module):
    def __init__(self, dimension_out: typing.SupportsInt | typing.SupportsIndex, device: torch.device = ..., dtype: torch.dtype = ...) -> None:
        ...
    def forward(self, arg0: collections.abc.Iterable | bytes, arg1: collections.abc.Iterable | bytes) -> torch.Tensor:
        """Return player embeddings with shape ``[B, 2, dimension_out]``. Raw ``bytes`` are
        accepted as a single-player batch of size one."""
        ...
    def load_weights(self, arg0: str) -> None:
        ...
    def save_weights(self, arg0: str) -> None:
        ...
class PlayerTargetDataEmbedding(torch._C.cpp.nn.Module):
    def __init__(self, shared_embedding_holder: SharedEmbeddingHolder, dimension_out: typing.SupportsInt | typing.SupportsIndex, device: torch.device = ..., dtype: torch.dtype = ...) -> None:
        ...
    def forward(self, arg0: torch.Tensor) -> torch.Tensor:
        ...
    def load_weights(self, arg0: str) -> None:
        ...
    def save_weights(self, arg0: str) -> None:
        ...
class PositionalEmbedding(torch._C.cpp.nn.Module):
    def __init__(self, d_model: typing.SupportsInt | typing.SupportsIndex, dropout: typing.SupportsFloat | typing.SupportsIndex = 0.1, max_len: typing.SupportsInt | typing.SupportsIndex = 5000, device: torch.device = ..., dtype: torch.dtype = ...) -> None:
        ...
    def forward(self, arg0: torch.Tensor) -> torch.Tensor:
        ...
    def forward_packed(self, arg0: torch.Tensor, arg1: torch.Tensor) -> torch.Tensor:
        ...
class ReturnToDeckTypeDataEmbedding(torch._C.cpp.nn.Module):
    def __init__(self, shared_embedding_holder: SharedEmbeddingHolder, dimension_out: typing.SupportsInt | typing.SupportsIndex, device: torch.device = ..., dtype: torch.dtype = ...) -> None:
        ...
    def forward(self, arg0: torch.Tensor) -> torch.Tensor:
        ...
    def load_weights(self, arg0: str) -> None:
        ...
    def save_weights(self, arg0: str) -> None:
        ...
class SharedEmbeddingHolder(torch._C.cpp.nn.Module):
    def __init__(self, dimension_out: typing.SupportsInt | typing.SupportsIndex, device: torch.device = ..., dtype: torch.dtype = ...) -> None:
        ...
    def load_weights(self, arg0: str) -> None:
        ...
    def save_weights(self, arg0: str) -> None:
        ...
def make_card_embedding(
    shared_embedding_holder: SharedEmbeddingHolder | None,
    dimension_out: typing.SupportsInt | typing.SupportsIndex,
    device: torch.device = ...,
    dtype: torch.dtype = ...,
) -> CardEmbedding:
    """Test/debug helper. ``shared_embedding_holder`` is caller-owned; use ``GameEmbedding`` for training persistence."""
    ...
def make_card_state_embedding(dimension_out: typing.SupportsInt | typing.SupportsIndex, device: torch.device = ..., dtype: torch.dtype = ...) -> CardStateEmbedding:
    ...
def nesting_flatten_filter(arg0: collections.abc.Iterable) -> tuple[list[list[int]], list, dict]:
    ...
def nesting_reduce(arg0: torch.Tensor, arg1: list, arg2: dict, arg3: collections.abc.Callable) -> list:
    ...
def nesting_traverse_filter(arg0: collections.abc.Iterable) -> list:
    ...
