from __future__ import annotations
import collections.abc
import torch
import torch._C.cpp.nn
import typing
__all__: list[str] = ['AttackDataEmbedding', 'CardAmountDataEmbedding', 'DiscardDataEmbedding', 'FilterConditionEmbedding', 'FilterEmbedding', 'InstructionDataEmbedding', 'InstructionEmbedding', 'MultiHeadAttention', 'NormalizedLinear', 'PlayerTargetDataEmbedding', 'PositionalEmbedding', 'ReturnToDeckTypeDataEmbedding', 'SharedEmbeddingHolder', 'nesting_flatten_filter', 'nesting_is_prefix', 'nesting_reduce', 'nesting_traverse_filter']
class AttackDataEmbedding(torch._C.cpp.nn.Module):
    def __init__(self, dimension_out: typing.SupportsInt | typing.SupportsIndex, device: torch.device = ..., dtype: torch.dtype = ...) -> None:
        ...
    def forward(self, arg0: torch.Tensor) -> torch.Tensor:
        ...
    def load_weights(self, arg0: str) -> None:
        ...
    def save_weights(self, arg0: str) -> None:
        ...
class CardAmountDataEmbedding(torch._C.cpp.nn.Module):
    def __init__(self, shared_embedding_holder: SharedEmbeddingHolder, dimension_out: typing.SupportsInt | typing.SupportsIndex, device: torch.device = ..., dtype: torch.dtype = ...) -> None:
        ...
    def forward(self, arg0: torch.Tensor) -> torch.Tensor:
        ...
    def load_weights(self, arg0: str) -> None:
        ...
    def save_weights(self, arg0: str) -> None:
        ...
class DiscardDataEmbedding(torch._C.cpp.nn.Module):
    def __init__(self, dimension_out: typing.SupportsInt | typing.SupportsIndex, device: torch.device = ..., dtype: torch.dtype = ...) -> None:
        ...
    def forward(self, arg0: torch.Tensor) -> torch.Tensor:
        ...
    def load_weights(self, arg0: str) -> None:
        ...
    def save_weights(self, arg0: str) -> None:
        ...
class FilterConditionEmbedding(torch._C.cpp.nn.Module):
    def __init__(self, shared_embedding_holder: SharedEmbeddingHolder, dimension_out: typing.SupportsInt | typing.SupportsIndex, device: torch.device = ..., dtype: torch.dtype = ...) -> None:
        ...
    def forward(self, arg0: torch.Tensor, arg1: torch.Tensor, arg2: torch.Tensor) -> torch.Tensor:
        ...
    def load_weights(self, arg0: str) -> None:
        ...
    def save_weights(self, arg0: str) -> None:
        ...
class FilterEmbedding(torch._C.cpp.nn.Module):
    def __init__(self, shared_embedding_holder: SharedEmbeddingHolder, dimension_out: typing.SupportsInt | typing.SupportsIndex, device: torch.device = ..., dtype: torch.dtype = ...) -> None:
        ...
    def forward(self, arg0: collections.abc.Iterable) -> torch.Tensor:
        ...
    def load_weights(self, arg0: str) -> None:
        ...
    def save_weights(self, arg0: str) -> None:
        ...
class InstructionDataEmbedding(torch._C.cpp.nn.Module):
    def __init__(self, shared_embedding_holder: SharedEmbeddingHolder, dimension_out: typing.SupportsInt | typing.SupportsIndex, device: torch.device = ..., dtype: torch.dtype = ...) -> None:
        ...
    def forward(self, arg0: torch.Tensor, arg1: torch.Tensor, arg2: torch.Tensor, arg3: tuple, arg4: tuple, arg5: typing.SupportsInt | typing.SupportsIndex) -> torch.Tensor:
        ...
    def load_weights(self, arg0: str) -> None:
        ...
    def save_weights(self, arg0: str) -> None:
        ...
class InstructionEmbedding(torch._C.cpp.nn.Module):
    def __init__(self, instruction_data_embedding: InstructionDataEmbedding, shared_embedding_holder: SharedEmbeddingHolder, dimension_out: typing.SupportsInt | typing.SupportsIndex, device: torch.device = ..., dtype: torch.dtype = ...) -> None:
        ...
    def compute_data_tensors(self, arg0: collections.abc.Iterable) -> torch.Tensor:
        ...
    def compute_instruction_embeddings(self, arg0: collections.abc.Iterable) -> torch.Tensor:
        ...
    def forward(self, arg0: collections.abc.Iterable) -> torch.Tensor:
        ...
    def load_weights(self, arg0: str) -> None:
        ...
    def save_weights(self, arg0: str) -> None:
        ...
class MultiHeadAttention(torch._C.cpp.nn.Module):
    def __init__(self, d_q: typing.SupportsInt | typing.SupportsIndex, d_k: typing.SupportsInt | typing.SupportsIndex, d_v: typing.SupportsInt | typing.SupportsIndex, d_head: typing.SupportsInt | typing.SupportsIndex, nheads: typing.SupportsInt | typing.SupportsIndex, dropout: typing.SupportsFloat | typing.SupportsIndex = 0.0, bias: bool = True, device: torch.device = ..., dtype: torch.dtype = ...) -> None:
        ...
    def forward(self, arg0: torch.Tensor, arg1: torch.Tensor, arg2: torch.Tensor, arg3: torch.Tensor | None, arg4: bool) -> torch.Tensor:
        ...
    def load_weights(self, arg0: str) -> None:
        ...
    def save_weights(self, arg0: str) -> None:
        ...
class NormalizedLinear(torch._C.cpp.nn.Module):
    def __init__(self, d_in: typing.SupportsInt | typing.SupportsIndex, d_out: typing.SupportsInt | typing.SupportsIndex, divisor: typing.SupportsFloat | typing.SupportsIndex = 400.0, device: torch.device = ..., dtype: torch.dtype = ...) -> None:
        ...
    def forward(self, arg0: torch.Tensor) -> torch.Tensor:
        ...
    def load_weights(self, arg0: str) -> None:
        ...
    def save_weights(self, arg0: str) -> None:
        ...
class PlayerTargetDataEmbedding(torch._C.cpp.nn.Module):
    def __init__(self, shared_embedding_holder: SharedEmbeddingHolder, dimension_out: typing.SupportsInt | typing.SupportsIndex, device: torch.device = ..., dtype: torch.dtype = ...) -> None:
        ...
    def forward(self, arg0: torch.Tensor) -> torch.Tensor:
        ...
    def load_weights(self, arg0: str) -> None:
        ...
    def save_weights(self, arg0: str) -> None:
        ...
class PositionalEmbedding(torch._C.cpp.nn.Module):
    def __init__(self, d_model: typing.SupportsInt | typing.SupportsIndex, dropout: typing.SupportsFloat | typing.SupportsIndex = 0.1, max_len: typing.SupportsInt | typing.SupportsIndex = 5000, device: torch.device = ..., dtype: torch.dtype = ...) -> None:
        ...
    def forward(self, arg0: torch.Tensor) -> torch.Tensor:
        ...
class ReturnToDeckTypeDataEmbedding(torch._C.cpp.nn.Module):
    def __init__(self, shared_embedding_holder: SharedEmbeddingHolder, dimension_out: typing.SupportsInt | typing.SupportsIndex, device: torch.device = ..., dtype: torch.dtype = ...) -> None:
        ...
    def forward(self, arg0: torch.Tensor) -> torch.Tensor:
        ...
    def load_weights(self, arg0: str) -> None:
        ...
    def save_weights(self, arg0: str) -> None:
        ...
class SharedEmbeddingHolder(torch._C.cpp.nn.Module):
    def __init__(self, dimension_out: typing.SupportsInt | typing.SupportsIndex, device: torch.device = ..., dtype: torch.dtype = ...) -> None:
        ...
    def load_weights(self, arg0: str) -> None:
        ...
    def save_weights(self, arg0: str) -> None:
        ...
def nesting_flatten_filter(arg0: collections.abc.Iterable) -> tuple[list[list[int]], list, dict]:
    ...
def nesting_is_prefix(arg0: tuple, arg1: tuple) -> bool:
    ...
def nesting_reduce(arg0: torch.Tensor, arg1: list, arg2: dict, arg3: collections.abc.Callable) -> list:
    ...
def nesting_traverse_filter(arg0: collections.abc.Iterable) -> list:
    ...
